- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}" #if we did not defined variables we can directly give value here using "defualt"

  - name: convert string to list
    vars:
      fruits: "apple, banana, orange" #these are String 
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}" # we can convert strings to list type using "split{{','}}"


  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"

  - name: convert upper to lower
    tags:
    - uppertolower
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: convert lower to upper
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}" # it will all latters upper case of shivakumar reddy m

  - name: print min and max
    vars:
      numbers: [1,30,57,87,98,46845]
    ansible.builtin.debug:
      msg: "Min is: {{ numbers | min }}, Max is: {{ numbers | max }}"

  - name: check ipaddress is valid or not
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:   # if we et error to installl python, install "pip" (by checking ansible --version)
      msg: "{{ ip | ansible.utils.ipaddr }}" # it will check the the ip is valid or not