- name: install and run nginx  #mmost importent in interviews
  hosts: 172.31.27.253
  become: yes # -b
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
